### ISSUE TITLE
build fails with issue with rss blade source template

### ISSUE THREAD

**Issue by chrismccoy** [tightenco/jigsaw-blog-template#25]
Tried building the docs template which worked fine, when building the blog template it errors at the build stage for the rss template

    In b1bd50064881d5d5fd15ab8102895a60541340af.php line 1:

      syntax error, unexpected 'version' (T_STRING) (View: /home/chris/blog/sourc
      e/_layouts/rss.blade.php) (View: /home/chris/blog/source/_layouts/rss.blade
      .php)

    build [--pretty PRETTY] [-c|--cache [CACHE]] [--] [<env>]

**Comment by damiani** [comment]
I can't reproduce this issue; did you alter `rss.blade.php` in any way? Can you tell me a little bit about your system setup?

**Comment by chrismccoy** [comment]
https://asciinema.org/a/tXpjZRjcHddYf9AwVGZYYmn0m

here is a quick video of me building it.

on ubuntu with php v7.2.13, node v10.14.2 and npm v6.5.0

**Comment by damiani** [comment]
I just pushed an update to the blog template (v1.0.3) that should fix the issue...could you give it a shot on a fresh install?

**Comment by chrismccoy** [comment]
yes, builds fine now, thanks
