### ISSUE TITLE
archive page

### ISSUE THREAD

**Issue by diomed** [tightenco/jigsaw-blog-template#27]
hello

could it be possible to have archive page to come along with a blog template?
seems to be only thing that's kinda missing.

**Comment by diomed** [comment]
btw. why is there a file called bootstrap.php if this is built with tailwind?

**Comment by vmitchell85** [comment]
@diomed One definition of bootstrap is:

> a technique of loading a program into a computer by means of a few initial instructions that enable the introduction of the rest of the program from an input device.

This doesn't mean Twitter's Bootstrap framework.

**Comment by damiani** [comment]
I think we'll leave this out of the template.
