### ISSUE TITLE
class is too close

### ISSUE THREAD

**Issue by diomed** [tightenco/jigsaw-blog-template#36]
can someone please check source of this template in Firefox's source preview.

as you can see here:

```
<a href="http://jigsaw-blog-staging.tighten.co/blog/getting-started" title="Read - Getting Started"class="uppercase tracking-wide mb-4">
```

class is too close to " and that's a minor bug.
might be good to fix it - since Firefox shows it as invalid few times in source code.

**Comment by damiani** [comment]
Addressed in #37
