### ISSUE TITLE
sticky header / back to top

### ISSUE THREAD

**Issue by diomed** [tightenco/jigsaw-blog-template#38]
would be nice if template had both of these

**Comment by diomed** [comment]
would be really good if sticky header is like this:
https://wicky.nillia.ms/headroom.js/

**Comment by diomed** [comment]
any news on this ⁉️

**Comment by diomed** [comment]
any news on this ⁉️

**Comment by diomed** [comment]
any news on this ⁉️

**Comment by bakerkretzmar** [comment]
The sticky header looks nice, feel free to submit a PR!
