### ISSUE TITLE
Disqus Comments

### ISSUE THREAD

**Issue by atymic** [tightenco/jigsaw-blog-template#49]
Hey!

I was wondering you you'd be open adding disqus comments to the blog template?
I wrote a post on how to do it [here](https://atymic.dev/blog/jigsaw-disqus-comments/) but I think it would be a good feature to have integrated.

Let me know, would be happy to PR.

**Comment by mattstauffer** [comment]
Hey @atymic! Thanks for sharing! I don't think we want to have this included in the template out of the box, but we have two other options:

1. We'd love to link that article at https://builtwithjigsaw.com/ if that's OK by you
2. We intend to add a section to the docs with solutions for common tasks and this would be a wonderful fit for it, if you wouldn't mind either helping us repurpose it for that (with attribution) or link to it. We're not there quite yet but hope to get to it soon.

**Comment by atymic** [comment]
> We'd love to link that article at builtwithjigsaw.com if that's OK by you

That would be fine, no worries.

> We intend to add a section to the docs with solutions for common tasks and this would be a wonderful fit for it, if you wouldn't mind either helping us repurpose it for that (with attribution) or link to it. We're not there quite yet but hope to get to it soon.

Either is fine by me :)
I'll have a look at the docs and see if I can make a PR.

**Comment by atymic** [comment]
Would you like me to make a PR against the docs?
