### ISSUE TITLE
No package-lock.json

### ISSUE THREAD

**Issue by cameron-elliott** [tightenco/jigsaw-blog-template#53]
This keeps bothering me, so I am sorry I have to say something! Ack!

Anyway, the 'docs' template has a package-lock.json file in the root, but the 'blog'
template does not.
Is that by design or another reason?

https://docs.npmjs.com/files/package-lock.json

"This file is intended to be committed into source repositories, and serves various purposes: ..."

**Comment by mattstauffer** [comment]
They're certainly not different on purpose. I don't know whether I would want it committed, though--often you want people to get the freshest version of all dependencies. See, for example, Laravel not having it. I'm a *bit* inclined to not have it in either but I'm not 100% sure.
