### ISSUE TITLE
Difference in NPM local and production css compilation of mailchimp 

### ISSUE THREAD

**Issue by nabeelahmeddaraz** [tightenco/jigsaw-blog-template#55]
This code in `_mailchimp.scss`:
```
    div.mc-field-group {
        > div.mce_inline_error {
            @apply .bg-transparent;
            @apply .float-left;
            @apply .font-semibold;
            @apply .p-0;
            @apply .text-grey-darker;

            clear: both;
        }
    }
```
It compiles fine on `npm run dev` and resulting css file has above classes:
![image](https://user-images.githubusercontent.com/25764411/71723337-1aca1700-2e4e-11ea-8110-1f5c54cb6dfb.png)
![image](https://user-images.githubusercontent.com/25764411/71723447-7dbbae00-2e4e-11ea-81e7-c66c17128fbb.png)

But on `npm run production`, resulting css does not have above classes, hence it uses default styling from mailchimp and does not go with the rest of the design.
![image](https://user-images.githubusercontent.com/25764411/71723411-5e248580-2e4e-11ea-9451-fe0d5f6a17ea.png)
![image](https://user-images.githubusercontent.com/25764411/71723427-6a104780-2e4e-11ea-84e9-17d9d03f4903.png)

Any idea why could it be happening?

Thanks.

**Comment by damiani** [comment]
Looks like we need to whitelist Mailchimp's styles so they don't get removed by PurgeCSS. If you add `/mce/` to the `.purgeCss` declaration in `webpack.mix.js`, it should work correctly:

```
    .purgeCss({
        extensions: ['html', 'md', 'js', 'php', 'vue'],
        folders: ['source'],
        whitelistPatterns: [/language/, /hljs/, /mce/],
    })
```

Give that a shot, and let me know.

**Comment by nabeelahmeddaraz** [comment]
Yup, that was the problem. Whitelisting fixed the issue. ✅ 

Thanks for the quick resolution!

Created PR to fix this:
https://github.com/tightenco/jigsaw-blog-template/pull/56

**Comment by damiani** [comment]
Great, thanks for the PR!
