### ISSUE TITLE
Strange Build problem

### ISSUE THREAD

**Issue by kapsoft** [tightenco/jigsaw-blog-template#59]
I have a wordpress blog I am trying to move over to jigsaw blog template. I have a large amount of markdown files (~200) I am trying to bring in. Doing a few files at a time is fine, but at a certain point I get the error (below) that I have no clue how to fix. Once this happens I have to re-init the template to get back. Pretty much stuck on this. I can't seem to tie it to something in the file(s). Any help is appreciate (love your work here). DJK

(base) Apple:Deanonsoftware apple$ ./vendor/bin/jigsaw build

Building local site 
Building files from source...

PHP Notice:  A non well formed numeric value encountered in /Users/apple/Deanonsoftware/cache/98aae06b1d504cdda44e9b5acdb9dc2a31fd50ae.php on line 15
PHP Notice:  A non well formed numeric value encountered in /Users/apple/Deanonsoftware/cache/42ffd2601059e747fee5c0b2cb663d37812f0146.php on line 5
PHP Notice:  A non well formed numeric value encountered in /Users/apple/Deanonsoftware/cache/42ffd2601059e747fee5c0b2cb663d37812f0146.php on line 6

In Factory.php line 161:
                                                                               
  None of the views in the given array exist. (View: /Users/apple/Deanonsoftw  
  are/source/_components/post-as-rss-item.blade.php) (View: /Users/apple/Dean  
  onsoftware/source/_components/post-as-rss-item.blade.php)                    
                                                                               

In Factory.php line 161:
                                                                               
  None of the views in the given array exist. (View: /Users/apple/Deanonsoftw  
  are/source/_components/post-as-rss-item.blade.php)                           
                                                                               

In Factory.php line 161:
                                               
  None of the views in the given array exist.  
                                               

build [--pretty PRETTY] [-c|--cache [CACHE]] [--] [<env>]

(base) Apple:Deanonsoftware apple$

**Comment by bakerkretzmar** [comment]
Did you manage to figure this out? If not, can you provide more information about when and how that error is happening? An example file that seems to have this issue, of the contents of your `post-as-rss-item.blade.php`? Thanks.

**Comment by kapsoft** [comment]
Thanks for getting back. I did solve it a while back. There was an extra field in the header of markup file(s). I referenced your example and solved.

**Comment by warren5236** [comment]
For anyone else coming here, I also had this problem and it was because there was a period in the filename of my post.
