### ISSUE TITLE
Incomplete (stripped) 1st production build 

### ISSUE THREAD

**Issue by iainheng** [tightenco/jigsaw-blog-template#65]
I found a weird bug where the 1st production build with `npm run production` will produce incomplete `build/css/main.css`. However subsequent builds will correct the issue itself. 

I am trying with the sample jigsaw blog `$ ./vendor/bin/jigsaw init blog`. I deleted the `build/` folder and run `npm run production` for the 1st time
![image](https://user-images.githubusercontent.com/3263759/55050483-f0138c80-508b-11e9-88a2-df2b2c8ca87d.png)
Notice the 11.4kb `main.css`

This is what I get in next build with `npm run production`
![image](https://user-images.githubusercontent.com/3263759/55050526-1e916780-508c-11e9-8562-1299c20edac5.png)
Here we have 12.4kb `main.css`

Here is the screenshot of code compare in VS code of these 2 different `main.css`
![image](https://user-images.githubusercontent.com/3263759/55050569-54cee700-508c-11e9-9cff-5f2cdf7dd58f.png)

My working environment:

OS: Window 10
node version: 10.15.3
npm version: 6.8.0
Laravel mix version: 4.0.14

**Comment by damiani** [comment]
Transferring this here, since it seems to be related to `purgeCss`, which is unique to the blog template. It doesn't affect a stock Jigsaw install.

**Comment by bakerkretzmar** [comment]
@iainheng can you confirm if you still have this issue? The blog template has changed a fair bit since we were last looking at this issue and I can no longer reproduce it on a fresh install.

**Comment by iainheng** [comment]
@bakerkretzmar sorry for my belated reply. Yes. I can confirm this issue is no longer exists after few tries I tried just now. 👍🏻

**Comment by bakerkretzmar** [comment]
Glad to hear it! Closing this now, if you're still seeing this on older sites, upgrading to use the new [`laravel-mix-jigsaw`](http://github.com/tightenco/laravel-mix-jigsaw) package should be enough to fix it. Feel free to comment or open another issue if you run into any problems doing that!
