### ISSUE TITLE
Where does $page->site_path come from? (rss.blade.php)

### ISSUE THREAD

**Issue by raniesantos** [tightenco/jigsaw-blog-template#66]
I also checked the Jigsaw docs and the source code itself, it's nowhere.

https://github.com/tightenco/jigsaw-blog-template/blob/8ba22f89261c57689a3d4eb691aed5558a660d8e/source/_layouts/rss.blade.php#L4

**Comment by raniesantos** [comment]
@mattstauffer you added that line so I hope you don't mind me tagging you.

**Comment by mattstauffer** [comment]
Hm. This is copied from my personal blog; in `source/blog/feed.blade.atom`, this is what mine looks like:

```
---
title: MattStauffer.com
site_path: blog
author: Matt Stauffer
---

@extends('_layouts.rss')

@section('entries')
    @foreach($posts as $entry)
        @include('_components.blog-as-rss-item')
    @endforeach
@endsection
```

That makes me think we modified it at some point in this template and didn't set that up correctly. But I'm kind of surprised that doesn't throw errors during generation. But yah, it seems like that's missing. Does that fix your problem? If so, we may need to fix the template.

Thanks!

**Comment by raniesantos** [comment]
Thanks for the reply.

I was actually just using this as a reference for generating a feed in my own template. I noticed it and it bugged me that I don't know what that property was for. The fact that it threw no errors just confused me even more. var_dump-ing it gives null.

Anyway, I'm closing the issue. I hope you could double check all the feed-related code as well since I'm referencing them right now.

**Comment by damiani** [comment]
That should have been defined in the YAML header for `feed.blade.atom` (like Matt has it on his blog); it specifies the root of the RSS content, which in the case of this template, lives at `/blog`. I've updated that in the template.
